version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "5000:5000"